version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: geneeez-postgres-db
    environment:
      POSTGRES_DB: geneeez
      POSTGRES_USER: geneeez
      POSTGRES_PASSWORD: geneeez_pw
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo:6
    container_name: geneeez-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  pgdata: {}
  mongodata: {}
