import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from pathlib import Path
from datetime import datetime
import pandas as pd, numpy as np
from sqlalchemy.orm import Session
from app.models import AnalysisRun, RunStatus, Dataset
from app.config import settings
import os, re

STORAGE_ROOT = Path(settings.STORAGE_DIR)
UPLOAD_ROOT  = Path(settings.UPLOAD_DIR)

UPLOAD_ROOT = Path(settings.UPLOAD_DIR).resolve()
ALLOWED_EXTS = {".parquet", ".pq", ".csv", ".tsv", ".txt", ".xlsx", ".xls"}
BASE = settings.PUBLIC_API_BASE.rstrip("/")

def _dataset_dir(ds) -> Path:
    p = Path(ds.storage_path)
    return p.parent if p.exists() else (UPLOAD_ROOT / str(ds.owner_id) / str(ds.id))
def _autogroup_meta(df: pd.DataFrame, group_col: str, ds) -> pd.DataFrame:
    """
    Make a fake metadata with two groups:
    1) Try to infer groups from sample names by keywords.
    2) Fallback to k-means (k=2) on samples in expression space.
    Writes sample_meta_autogenerated.csv in the dataset folder and returns it.
    """
    ds_dir = _dataset_dir(ds)
    num = df.select_dtypes(include=np.number).copy()
    cols = list(num.columns)
    if len(cols) < 4:
        raise ValueError("Need ≥4 samples to auto-group.")

    # 1) Try name keywords
    names = pd.Series(cols, dtype=str).str.lower()
    a_kw = names.str.contains(r"(control|ctrl|wt|normal)")
    b_kw = names.str.contains(r"(treated|case|mut|tumor|ko|kd)")

    if a_kw.any() and b_kw.any():
        grp = np.where(a_kw, "A", np.where(b_kw, "B", None))
        meta = pd.DataFrame({"sample_id": cols, group_col: grp}).dropna()
        if meta[group_col].nunique() == 2:
            outp = ds_dir / "sample_meta_autogenerated.csv"
            meta.to_csv(outp, index=False)
            return meta

    # 2) Fallback: k-means on PCA of samples
    from sklearn.preprocessing import StandardScaler
    from sklearn.decomposition import PCA
    from sklearn.cluster import KMeans

    X = StandardScaler().fit_transform(num.T.values)             # samples × genes
    n_pc = max(2, min(10, X.shape[1] - 1))
    PCs = PCA(n_components=n_pc, random_state=0).fit_transform(X)
    km = KMeans(n_clusters=2, n_init=10, random_state=0).fit(PCs)

    labels = np.where(km.labels_ == 0, "A", "B")
    meta = pd.DataFrame({"sample_id": cols, group_col: labels})
    outp = ds_dir / "sample_meta_autogenerated.csv"
    meta.to_csv(outp, index=False)
    return meta


def _read_sample_meta(ds, group_col: str = "group") -> pd.DataFrame:
    ds_dir = _dataset_dir(ds)
    candidates = ["sample_meta.csv", "sample_metadata.csv", "metadata.csv"]
    for name in candidates:
        fp = ds_dir / name
        if fp.exists():
            meta = pd.read_csv(fp)
            cols = {c.lower(): c for c in meta.columns}
            if "sample_id" not in cols or group_col.lower() not in cols:
                raise ValueError(
                    f"Metadata {fp.name} must have columns: sample_id,{group_col}"
                )
            meta = meta[[cols["sample_id"], cols[group_col.lower()]]].copy()
            meta.columns = ["sample_id", group_col]
            meta["sample_id"] = meta["sample_id"].astype(str)
            meta[group_col] = meta[group_col].astype(str)
            return meta

    # Create a template to help the user
    expr = pd.read_parquet(_dataset_dir(ds) / "matrix.parquet") \
        if (_dataset_dir(ds) / "matrix.parquet").exists() \
        else pd.read_csv(_dataset_dir(ds) / "matrix.csv")
    expr_cols = [c for c in expr.columns if c.lower() != "gene_id"]
    template = pd.DataFrame({"sample_id": expr_cols, group_col: ""})
    tmpl_path = _dataset_dir(ds) / "sample_meta_template.csv"
    template.to_csv(tmpl_path, index=False)

    raise FileNotFoundError(
        f"Sample metadata not found. I wrote a template at {tmpl_path}. "
        f"Fill '{group_col}' for exactly two groups (≥2 samples each) and rerun."
    )

def _bh_fdr(pvals: np.ndarray) -> np.ndarray:
    """Benjamini–Hochberg FDR."""
    m = len(pvals)
    order = np.argsort(pvals)
    ranked = pvals[order]
    fdr = ranked * m / (np.arange(m) + 1)
    fdr = np.minimum.accumulate(fdr[::-1])[::-1]
    out = np.empty_like(fdr)
    out[order] = fdr
    return np.clip(out, 0, 1)

def _log(msg, *args):
    print("[analytics]", msg.format(*args))

def _slug(s: str) -> str:
    try:
        return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")
    except Exception:
        return ""

def _pick_best(files: list[Path]) -> Path:
    pref = {".parquet":0, ".pq":0, ".csv":1, ".tsv":2, ".txt":3, ".xlsx":4, ".xls":4}
    files.sort(key=lambda p: (pref.get(p.suffix.lower(), 99), -p.stat().st_size))
    return files[0]

def _dataset_path(ds: Dataset) -> Path:
    """
    Find the dataset file under uploads/<owner_id>/... (your layout),
    with helpful logs at every step. Falls back to a sensible single file
    if no exact match by id/title is found.
    """
    _log("cwd: {}", Path(os.getcwd()).resolve())
    _log("UPLOAD_ROOT: {}", UPLOAD_ROOT)
    _log("dataset id={}, owner_id={}, title={!r}", ds.id, getattr(ds, "owner_id", None), getattr(ds, "title", None))

    for attr in ("file_path", "path", "storage_uri", "local_path"):
        v = getattr(ds, attr, None)
        _log("check attr {} -> {}", attr, v)
        if v:
            p = Path(v)
            _log("  exists={} resolved={}", p.exists(), p.resolve())
            if p.exists():
                _log("using direct path: {}", p)
                return p

    owner_id = str(getattr(ds, "owner_id", "") or "")
    user_dir = (UPLOAD_ROOT / owner_id)
    _log("user_dir {}", user_dir)

    if not user_dir.exists():
        try:
            sample = [str(p) for p in list(UPLOAD_ROOT.iterdir())[:20]]
        except FileNotFoundError:
            sample = ["<uploads dir missing>"]
        _log("user_dir missing. top-level under uploads: {}", sample)
        raise ValueError("Dataset file path not found (user dir missing)")

    def collect(base: Path, limit=5000) -> list[Path]:
        files = []
        for i, p in enumerate(base.rglob("*")):
            if i > limit:
                _log("scan limit {} reached under {}", limit, base)
                break
            try:
                if p.is_file() and p.suffix.lower() in ALLOWED_EXTS:
                    files.append(p)
            except Exception:
                pass
        return files

    id_pat = str(ds.id)
    by_id = [p for p in collect(user_dir) if id_pat in str(p)]
    _log("matches containing dataset id '{}': {}", id_pat, len(by_id))
    if by_id:
        pick = _pick_best(by_id)
        _log("picked by id: {}", pick)
        return pick

    title = getattr(ds, "title", None)
    if title:
        tslug = _slug(title)
        by_title = [p for p in collect(user_dir) if tslug and tslug in str(p).lower()]
        _log("matches containing title slug '{}': {}", tslug, len(by_title))
        if by_title:
            pick = _pick_best(by_title)
            _log("picked by title: {}", pick)
            return pick

    all_files = collect(user_dir)
    _log("fallback candidates under user dir: {}", len(all_files))
    if all_files:
        pick = _pick_best(all_files)
        _log("picked fallback: {}", pick)
        return pick

    _log("_dataset_path FAILED for dataset {} (owner {})", ds.id, owner_id)
    raise ValueError("Dataset file path not found")

def _load_df(p: Path) -> pd.DataFrame:
    compression = "infer" if p.suffix.lower() == ".gz" or str(p).endswith(".txt.gz") else None
    name = p.name
    if name.endswith(".txt.gz"):
        ext = ".txt"
    elif name.endswith(".tsv.gz"):
        ext = ".tsv"
    elif name.endswith(".csv.gz"):
        ext = ".csv"
    else:
        ext = p.suffix.lower()

    if ext in (".txt", ".tsv"):
        return pd.read_csv(
            p, sep="\t", comment="!", compression=compression, engine="python"
        )

    if ext in (".csv",):
        return pd.read_csv(p, compression=compression)

    if ext in (".parquet", ".pq"):
        return pd.read_parquet(p)

    if ext in (".xlsx", ".xls"):
        return pd.read_excel(p)

    return pd.read_csv(p, compression=compression)


def _outdir(run_id: int) -> Path:
    out = STORAGE_ROOT / "runs" / str(run_id)
    out.mkdir(parents=True, exist_ok=True)
    return out
def _u(path: str) -> str:
    return f"{BASE}{path}"

def execute_inline(db: Session, run: AnalysisRun, ds):
    run.status = RunStatus.running
    run.started_at = datetime.utcnow()
    db.commit()

    p = _dataset_path(ds)
    df = _load_df(p)
    outdir = _outdir(run.id)
    arts = {}

    if run.recipe_key == "correlation":
        from scipy.cluster.hierarchy import linkage, leaves_list
        method = (run.params_json or {}).get("method", "spearman")
        mode   = (run.params_json or {}).get("axis", "samples")  
        max_n  = int((run.params_json or {}).get("max_n", 300))
        do_cluster = bool((run.params_json or {}).get("cluster", True))

        num = df.select_dtypes(include=np.number)

        if mode == "samples":
            X = num.iloc[:, :max_n]                
            corr = X.corr(method=method)
        else:  
            X = num.T                            
            keep = X.var(axis=0, skipna=True).nlargest(max_n).index
            corr = X[keep].corr(method=method)

        if do_cluster and corr.shape[0] > 2:
            order = leaves_list(linkage(corr.fillna(0.0).values, method="average"))
            corr = corr.iloc[order, order]

        outdir = _outdir(run.id)
        corr.to_csv(outdir / "correlation.csv")
        plt.figure(figsize=(6,5))
        plt.imshow(corr.values, aspect="auto")
        plt.colorbar(); plt.title(f"Correlation ({method})")
        plt.tight_layout(); plt.savefig(outdir / "correlation.png"); plt.close()

        arts = {
            "csv_url": _u(f"/files/runs/{run.id}/correlation.csv"),
            "pngs":   [_u(f"/files/runs/{run.id}/correlation.png")],
        }

    elif run.recipe_key == "pca":
        from sklearn.preprocessing import StandardScaler
        from sklearn.decomposition import PCA

        p = run.params_json or {}
        n_req      = int(p.get("n_components", 10))
        top_genes  = int(p.get("top_genes", 1000))   
        use_log1p  = bool(p.get("log1p", False))     

        num_df = df.select_dtypes(include=np.number).copy()     
        sample_ids = list(num_df.columns)

        if use_log1p:
            num_df = np.log1p(num_df)

        # choose top-N variable genes (rows) by variance across samples
        # use df['gene_id'] when present to carry gene names into loadings
        if "gene_id" in df.columns and df.columns[0].lower() == "gene_id":
            gene_ids_all = df["gene_id"].astype(str)
        else:
            # fallback: synthetic gene ids if not present
            gene_ids_all = pd.Index([f"gene_{i}" for i in range(len(df))], name="gene_id")

        # Align gene ids with numeric subset (same row order as df)
        # num_df has the same index as df
        variances = num_df.var(axis=1, skipna=True)
        k = int(min(top_genes, len(variances)))
        keep_idx = variances.nlargest(k).index
        M = num_df.loc[keep_idx]                   
        kept_gene_ids = gene_ids_all.loc[keep_idx].astype(str).to_numpy()

        X = M.T.values                             

        Xz = StandardScaler(with_mean=True, with_std=True).fit_transform(X)

        # n cannot exceed min(n_samples, n_features)
        n = max(2, min(n_req, Xz.shape[0], Xz.shape[1]))

        pca = PCA(n_components=n, svd_solver="auto", random_state=0)
        scores   = pca.fit_transform(Xz)          
        loadings = pca.components_.T               
        evr      = pca.explained_variance_ratio_   

        outdir = _outdir(run.id)

        # 1) scores per sample with sample_id
        scores_df = pd.DataFrame(scores, columns=[f"PC{i+1}" for i in range(n)])
        scores_df.insert(0, "sample_id", sample_ids)
        scores_df.to_csv(outdir / "pca_scores.csv", index=False)

        # 2) loadings per gene with gene_id
        load_df = pd.DataFrame(loadings, columns=[f"PC{i+1}" for i in range(n)])
        load_df.insert(0, "gene_id", kept_gene_ids)
        load_df.to_csv(outdir / "pca_loadings.csv", index=False)

        # 3) explained variance (+ cumulative) per PC
        explained_df = pd.DataFrame({
            "pc":        [f"PC{i+1}" for i in range(n)],
            "explained": evr,
            "cumulative": np.cumsum(evr)
        })
        explained_df.to_csv(outdir / "pca_explained.csv", index=False)

        # Scree with cumulative
        plt.figure()
        x = np.arange(1, n + 1)
        plt.plot(x, evr, marker="o", label="Explained")
        plt.plot(x, np.cumsum(evr), marker="o", linestyle="--", label="Cumulative")
        plt.xlabel("Principal component")
        plt.ylabel("Explained variance ratio")
        plt.title("PCA Scree")
        plt.legend()
        plt.tight_layout()
        plt.savefig(outdir / "pca_scree.png")
        plt.close()

        pc1_pct = round(100 * evr[0], 1) if n >= 1 else 0.0
        pc2_pct = round(100 * evr[1], 1) if n >= 2 else 0.0

        plt.figure()
        plt.scatter(scores[:, 0], scores[:, 1], s=12)
        plt.xlabel(f"PC1 ({pc1_pct}%)")
        plt.ylabel(f"PC2 ({pc2_pct}%)")
        plt.title("PCA (samples)")
        plt.tight_layout()
        plt.savefig(outdir / "pca_scatter.png")
        plt.close()

        arts = {
            "scores_csv":    _u(f"/files/runs/{run.id}/pca_scores.csv"),
            "loadings_csv":  _u(f"/files/runs/{run.id}/pca_loadings.csv"),
            "explained_csv": _u(f"/files/runs/{run.id}/pca_explained.csv"),
            "pngs": [
                _u(f"/files/runs/{run.id}/pca_scree.png"),
                _u(f"/files/runs/{run.id}/pca_scatter.png"),
            ],
        }

        from sklearn.preprocessing import StandardScaler
        from sklearn.decomposition import PCA

        p = run.params_json or {}
        n = int(p.get("n_components", 10))
        top_genes = int(p.get("top_genes", 1000))     
        use_log1p = bool(p.get("log1p", False))       

        M = df.select_dtypes(include=np.number).copy()
        if use_log1p:
            M = np.log1p(M)

        # keep top-N variable genes (rows if genes are rows; if genes are columns, transpose)
        # Our canonical matrix is genes in rows, samples in columns (first col 'gene_id').
        if "gene_id" in df.columns and df.columns[0].lower() == "gene_id":
            genes = df["gene_id"].astype(str).values
            X = M.values  
            if X.shape[0] > top_genes:
                keep_idx = np.argsort(X.var(axis=1))[-top_genes:]
                X = X[keep_idx, :]
                genes = genes[keep_idx]
            X = StandardScaler(with_mean=True, with_std=True).fit_transform(X)
            Xs = X.T
            pca = PCA(n_components=max(2, min(n, Xs.shape[1])))
            scores = pca.fit_transform(Xs)  
            loadings = pca.components_.T   
            pd.DataFrame(
                scores[:, :2], columns=["PC1","PC2"]
            ).to_csv(outdir/"pca_scores.csv", index=False)
            pd.DataFrame(
                loadings, index=genes, columns=[f"PC{i+1}" for i in range(pca.n_components_)]
            ).to_csv(outdir/"pca_loadings.csv")
        else:
            X = M.values.T
            X = StandardScaler(with_mean=True, with_std=True).fit_transform(X)
            pca = PCA(n_components=max(2, min(n, X.shape[1])))
            scores = pca.fit_transform(X)
            pd.DataFrame(scores[:, :2], columns=["PC1","PC2"]).to_csv(outdir/"pca_scores.csv", index=False)

        evr = pca.explained_variance_ratio_
        pc1_pct = round(100*evr[0], 1)
        pc2_pct = round(100*evr[1], 1)

        # Scree + cumulative
        plt.figure()
        x = np.arange(1, len(evr)+1)
        plt.plot(x, evr, marker="o", label="Explained")
        plt.plot(x, np.cumsum(evr), marker="o", linestyle="--", label="Cumulative")
        plt.xlabel("Principal component"); plt.ylabel("Explained variance ratio")
        plt.title("PCA Scree"); plt.legend(); plt.tight_layout()
        plt.savefig(outdir/"pca_scree.png"); plt.close()

        # Scatter
        plt.figure()
        plt.scatter(scores[:,0], scores[:,1], s=12)
        plt.xlabel(f"PC1 ({pc1_pct}%)"); plt.ylabel(f"PC2 ({pc2_pct}%)")
        plt.title("PCA (samples)"); plt.tight_layout()
        plt.savefig(outdir/"pca_scatter.png"); plt.close()

        arts = {
            "scores_csv": f"/files/runs/{run.id}/pca_scores.csv",
            "loadings_csv": f"/files/runs/{run.id}/pca_loadings.csv",
            "explained_csv": f"/files/runs/{run.id}/pca_explained.csv",
            "pngs": [
                f"/files/runs/{run.id}/pca_scree.png",
                f"/files/runs/{run.id}/pca_scatter.png",
            ],
        }

        from sklearn.preprocessing import StandardScaler
        from sklearn.decomposition import PCA

        num_df = df.select_dtypes(include=np.number)

        X = num_df.T.values  

        X = StandardScaler(with_mean=True, with_std=True).fit_transform(X)

        req_n = int((run.params_json or {}).get("n_components", 10))
        n = max(2, min(req_n, X.shape[1]))  

        pca = PCA(n_components=n, svd_solver="auto", random_state=0)
        scores = pca.fit_transform(X)  

        # Save PC1/PC2 coordinates per sample
        pc12 = pd.DataFrame(scores[:, :2], columns=["PC1", "PC2"])
        pc12.to_csv(outdir / "pca_scores.csv", index=False)

        # Scree plot
        plt.figure()
        plt.plot(np.arange(1, n + 1), pca.explained_variance_ratio_, marker="o")
        plt.xlabel("Principal component")
        plt.ylabel("Explained variance ratio")
        plt.title("PCA Scree")
        plt.tight_layout()
        plt.savefig(outdir / "pca_scree.png")
        plt.close()

        # Scatter of PC1 vs PC2 (samples)
        plt.figure()
        plt.scatter(pc12["PC1"], pc12["PC2"], s=12)
        plt.xlabel("PC1")
        plt.ylabel("PC2")
        plt.title("PCA (samples)")
        plt.tight_layout()
        plt.savefig(outdir / "pca_scatter.png")
        plt.close()

        arts = {
            "scores_csv": _u(f"/files/runs/{run.id}/pca_scores.csv"),
            "pngs": [
                _u(f"/files/runs/{run.id}/pca_scree.png"),
                _u(f"/files/runs/{run.id}/pca_scatter.png"),
            ],
            "explained_variance_ratio": pca.explained_variance_ratio_.tolist(),
        }

    elif run.recipe_key == "de":
        from scipy import stats

        # Params
        p = run.params_json or {}
        group_col = p.get("group_col", "group")
        alpha = float(p.get("alpha", 0.05))

        # Matrix (genes × samples) and gene ids
        if "gene_id" in df.columns and df.columns[0].lower() == "gene_id":
            gene_ids = df["gene_id"].astype(str)
            M = df.select_dtypes(include=np.number).copy()
            M.index = gene_ids
        else:
            # Fallback if first column wasn’t gene_id
            M = df.select_dtypes(include=np.number).copy()
            # invent simple gene ids
            M.index = [f"gene_{i}" for i in range(M.shape[0])]

        # Read metadata (sample_id, group_col)
        meta = _read_sample_meta(ds, group_col=group_col)

        # Align metadata to matrix columns
        common = [c for c in M.columns if c in set(meta["sample_id"])]
        if len(common) < 4:
            raise ValueError("Not enough overlapping samples between matrix and metadata.")
        M = M[common]
        try:
             meta = _read_sample_meta(ds, group_col=group_col)
        except FileNotFoundError:
            meta = _autogroup_meta(df, group_col, ds)

        groups = meta[group_col].unique()
        if len(groups) != 2:
            raise ValueError(f"DE requires exactly 2 groups in '{group_col}', found: {groups.tolist()}")

        gA, gB = groups[0], groups[1]
        A_cols = meta.loc[meta[group_col] == gA, "sample_id"].tolist()
        B_cols = meta.loc[meta[group_col] == gB, "sample_id"].tolist()
        if len(A_cols) < 2 or len(B_cols) < 2:
            raise ValueError("Each group must have at least 2 samples.")

        # Compute per-gene stats
        meanA = M[A_cols].mean(axis=1)
        meanB = M[B_cols].mean(axis=1)
        # Welch t-test
        tvals, pvals = stats.ttest_ind(M[A_cols].T, M[B_cols].T, equal_var=False, nan_policy="omit")
        # ttest_ind with DataFrames returns arrays aligned to rows
        # pvals -> array aligned with M.index
        pvals = np.asarray(pvals, dtype=float)
        fdr = _bh_fdr(np.nan_to_num(pvals, nan=1.0))

        res = pd.DataFrame({
            "gene_id": M.index,
            "mean_A": meanA.values,
            "mean_B": meanB.values,
            "log2fc": np.log2((meanB + 1e-9) / (meanA + 1e-9)),
            "t": np.asarray(tvals, dtype=float),
            "pval": pvals,
            "fdr": fdr,
        }).sort_values("pval", ascending=True)

        # Save results
        outdir = _outdir(run.id)
        res.to_csv(outdir / "de.csv", index=False)

        # Simple volcano (optional)
        try:
            plt.figure()
            plt.scatter(res["log2fc"], -np.log10(res["pval"] + 1e-300), s=6)
            sig = res["fdr"] < alpha
            if sig.any():
                plt.scatter(res.loc[sig, "log2fc"], -np.log10(res.loc[sig, "pval"] + 1e-300), s=6)
            plt.xlabel("log2 fold-change (B/A)")
            plt.ylabel("-log10 p-value")
            plt.title(f"Volcano ({gA} vs {gB})")
            plt.tight_layout()
            plt.savefig(outdir / "de_volcano.png")
            plt.close()
            volcano_url = _u(f"/files/runs/{run.id}/de_volcano.png")
        except Exception:
            volcano_url = None

        arts = {
            "csv_url": _u(f"/files/runs/{run.id}/de.csv"),
            "pngs": [u for u in [volcano_url] if u],
        }

        from scipy import stats

        def _bh_fdr(pvals: np.ndarray) -> np.ndarray:
            p = np.asarray(pvals, float)
            n = p.size
            order = np.argsort(p)
            ranks = np.arange(1, n + 1)
            adj = np.empty(n, float)
            adj[order] = np.minimum.accumulate((p[order] * n / ranks)[::-1])[::-1]
            return np.clip(adj, 0, 1)

        params = run.params_json or {}
        group_col = str(params.get("group_col", "group"))
        alpha = float(params.get("alpha", 0.05))

        # Expect canonical: gene_id + numeric sample columns
        if "gene_id" not in df.columns:
            raise ValueError("DE expects a canonical matrix with 'gene_id' + sample columns.")

        expr = df.set_index("gene_id").select_dtypes(include=np.number)  # genes x samples

        # Look for sample metadata in dataset folder
        ds_dir = Path(p).parent
        meta = None
        for cand in ["sample_meta.csv", "sample_metadata.csv", "metadata.csv"]:
            mp = ds_dir / cand
            if mp.exists():
                meta = pd.read_csv(mp)
                break

        if meta is None or "sample_id" not in meta.columns or group_col not in meta.columns:
            raise ValueError(
                f"Sample metadata not found. Put a CSV in {ds_dir} "
                f"with columns sample_id,{group_col} (e.g., sample_meta.csv)."
            )

        meta = meta.dropna(subset=["sample_id", group_col])
        meta[group_col] = meta[group_col].astype(str)

        # Keep only samples present in expression matrix
        meta = meta[meta["sample_id"].isin(expr.columns)]
        groups = sorted(meta[group_col].unique())
        if len(groups) != 2:
            raise ValueError(f"DE requires exactly 2 groups in '{group_col}', found: {groups}")

        g1, g2 = groups
        s1 = meta.loc[meta[group_col] == g1, "sample_id"].tolist()
        s2 = meta.loc[meta[group_col] == g2, "sample_id"].tolist()
        if len(s1) < 2 or len(s2) < 2:
            raise ValueError("Need at least 2 samples per group for a t-test.")

        # Welch t-test per gene
        rows = []
        for gene, row in expr.iterrows():
            a = row[s1].dropna().to_numpy(float)
            b = row[s2].dropna().to_numpy(float)
            if a.size < 2 or b.size < 2:
                pval = np.nan
                l2fc = np.nan
            else:
                t, pval = stats.ttest_ind(a, b, equal_var=False)
                # log2 fold change (group1 - group2)
                l2fc = float(np.log2(np.mean(a) + 1e-9) - np.log2(np.mean(b) + 1e-9))
            rows.append((gene, l2fc, pval))

        out = pd.DataFrame(rows, columns=["gene_id", "log2FC", "pval"]).dropna(subset=["pval"])
        out["fdr"] = _bh_fdr(out["pval"].values)
        out = out.sort_values("fdr")
        out.to_csv(outdir / "de.csv", index=False)

        # Volcano plot
        plt.figure()
        plt.scatter(out["log2FC"], -np.log10(out["pval"].clip(lower=1e-300)), s=6)
        plt.axhline(-np.log10(alpha), linestyle="--")
        plt.xlabel("log2 fold change"); plt.ylabel("-log10 p-value")
        plt.title(f"Differential Expression: {g1} vs {g2}")
        plt.tight_layout()
        plt.savefig(outdir / "de_volcano.png"); plt.close()

        arts = {
            "csv_url": _u(f"/files/runs/{run.id}/de.csv"),
            "pngs":   [_u(f"/files/runs/{run.id}/de_volcano.png")],
        }


    else:
        raise ValueError("Unsupported recipe")

    run.artifacts_json = arts
    run.status = RunStatus.succeeded
    run.finished_at = datetime.utcnow()
    db.commit()
